#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' @title Convert Markview Metabolomics file (alignment table) into 
#' a artMS compatible format
#' 
#' @description MarkerView is an ABSciex software that supports the files 
#' generated by Analyst software (.wiff) used to run our specific mass 
#' spectrometer (ABSciex Triple TOF 5600+). 
#' It also supports .t2d files generated by the 
#' Applied Biosystems 4700/4800 MALDI-TOF. 
#' Once the alignment is done by the software, 
#' it can also run statistical analysis 
#' (t-tests, unsupervised or supervised PCA). 
#' Moreover, it attempts to categorize features as "Monoisotopic" vs "Isotopic"
#'  if possible, allowing further filtering of the feature list.
#' The alignment table is automatically generated by Markerview and has a 
#' unique file type (.mrkvw). The table can be copied and pasted into Excel 
#' and then converted to a .txt file. Features identified as "isotopes" 
#' are removed before the table is generated. 
#' This file is further processed and formatted to perform QC and relative
#' quantification using the artMS functions
#' @param input_file (char) Markview input file
#' @param out_file (char) Output file name
#' @param id_file (char) KEGG database
#' @param verbose (logical) `TRUE` (default) shows function messages
#' @return (text file) Outputs the converted output name
#' @keywords metabolomics, convert
#' @examples \donttest{
#' artmsConvertMetabolomics(input_file = "markview-alignment.txt", 
#'                          out_file = "metabolomics-evidence.txt", 
#'                          id_file=NULL)
#' }
#' @export
artmsConvertMetabolomics <- function(input_file, 
                                out_file, 
                                id_file = NULL,
                                verbose = TRUE){
  
  if(missing(input_file))
    stop("Input file name <input_file> is missed")
  if(missing(out_file))
    stop("<out_file> is missed")
  
  if(verbose) message(">> Reading in data from: ", input_file," ")
  
  x <- fread(input_file)
  tmp <- melt(data=x, id=c(1:7), variable.name="RawFile", value.name="Intensity")
  
  tmp[,'Row'] = NULL
  tmp[,'Index'] = NULL
  setnames(tmp, c(1,3), c('Modified.sequence', 'Retention time'))
  tmp$Sequence <- gsub(' \\([0-9]+\\)', '', tmp$Sequence)
  tmp$Proteins <- tmp$Sequence
  tmp$Charge <- 1
  
  tmp <- as.data.frame(tmp, stringsAsFactors=F)
  
  # annotate with  known id's
  if(!is.null(id_file)){
    ids <- read.delim(id_file, stringsAsFactors=F, sep='\t')
    ids$KEGG <- gsub('\\\xca','',ids$KEGG)
    for( i in 1:length(ids$KEGG)){  #### This could be optimized!!!!!
      idx <- tmp$'m/z' %in% ids$m.z[i]
      tmp$Proteins[idx] = ids$KEGG[i]
    }
  }
  
  if(verbose) message(">> Writing out data to:", out_file, "... ")
  write.table(as.data.frame(tmp, stringsAsFactors=F), 
              out_file, 
              row.names=F, 
              col.names=T, 
              sep='\t', 
              quote=F)
  if(verbose) message('>> CONVERSION COMPLETE! ')
}


