#-------------------------------------------------------------------------------
#' @title Generate Phosfate Input file
#' 
#' @description It takes as input the `imputedL2fcExtended.txt` results
#' generated by the `artms_analysisQuantifications()` function and generates
#' the [Phosfate](http://phosfate.com/) input file
#' @param inputFile (char) the `imputedL2fcExtended.txt` file name and location
#' @return Multiple output files (inputs of phosfate)
#' @keywords generate, outputs, files
#' @examples \donttest{
#' artmsPhosfateOutput(inputFile)
#' }
#' @export
artmsPhosfateOutput <- function(inputFile){

  df <- .artms_checkIfFile(inputFile)
  
  if( !any(grepl("Protein", colnames(df))) ){
    stop("THE COLUMN 'Protein' was not found.
         Are you sure this is the right file?\n")
  }
  
  if( !any(grepl("PTMsite", colnames(df))) ){
    stop("THE COLUMN 'PTMsite' was not found.
         Are you sure this is the right file?\n")
  }
  
  if( !any(grepl("iLog2FC", colnames(df))) ){
    stop("THE COLUMN 'iLog2FC' was not found.
         Are you sure this is the right file?\n")
  }
  
  if( !any(grepl("Comparison", colnames(df))) ){
    stop("THE COLUMN 'Comparison' was not found.
         Are you sure this is the right file?\n")
  }
    
  output_dir <- "phosfate_input_files"
  # create output directory if it doesn't exist
  if(!dir.exists(output_dir)){
    dir.create(output_dir, recursive = T)
  }
  
  conditions <- unique(df$Comparison)
  
  for (i in 1:length(conditions)){
    cat(i," ", conditions[i],"\n")
    df.select <- df[which(df$Comparison == conditions[i]),]
    df.out <- df.select[c('Protein','PTMsite','iLog2FC')]
    fileout <- gsub(".txt","", inputFile)
    fileout <- paste0(fileout,"-",conditions[i],".txt")
    fileout <- paste0(output_dir,"/",fileout)
    write.table(df.out, fileout, col.names = F, row.names = F, quote = F, sep = ",")
    cat("\t",fileout," is out\n")
  }
}

