#-------------------------------------------------------------------------------
#' @title Generate Phosfate Input file
#' 
#' @description It takes as input the `imputedL2fcExtended.txt` results
#' generated by the `artms_analysisQuantifications()` function and generates
#' the [Phosfate](http://phosfate.com/) input file (or data.frame)
#' @param inputFile (char) the `imputedL2fcExtended.txt` file name and location
#' @param outputDir (char) Name of the folder to output results 
#' (Default: "phosfate_input_files")
#' @return Multiple output files (inputs of phosfate)
#' @keywords generate, outputs, files
#' @examples \donttest{
#' artmsPhosfateOutput(inputFile)
#' }
#' @export
artmsPhosfateOutput <- function(inputFile, 
                                outputDir = "phosfate_input_files"){

  df <- .artms_checkIfFile(inputFile)
  
  # Check the existance of the columns that are needed.
  checkColumns <- c('Protein', 'PTMsite', 'iLog2FC', 'Comparison')
  
  if (any( !checkColumns %in% colnames(df)) ) {
    stop("One (or many) column names are not found:\n",sprintf('%s, ',checkColumns))
  }
    
  # create output directory if it doesn't exist
  if(!dir.exists(outputDir)){
    dir.create(outputDir, recursive = TRUE)
  }
  
  conditions <- unique(df$Comparison)
  
  for ( i in seq_len(length(conditions)) ){
    cat(i," ", conditions[i],": ")
    df.select <- df[which(df$Comparison == conditions[i]),]
    df.out <- df.select[c('Protein','PTMsite','iLog2FC')]
    fileout <- gsub(".txt","", inputFile)
    fileout <- paste0(fileout,"-",conditions[i],".txt")
    fileout <- paste0(outputDir,"/",fileout)
    write.table(df.out, fileout, col.names = FALSE, row.names = FALSE, quote = FALSE, sep = ",")
    cat(fileout," is out\n")
  }
}

